M48
; DRILL file {KiCad 8.0.9-8.0.9-0~ubuntu24.04.1} date 2025-04-16T18:13:37-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-04-16T18:13:37-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.9-8.0.9-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
%
G90
G05
T1
X3.7894Y-4.7736
X6.5453Y-4.7736
M30
